site_name: Template for MkDocs
dev_addr: "127.0.0.1:8003"
theme: 
  name: material
  palette:
    scheme: dracula 
    primary: deep purple 
    accent: deep purple 
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.indexes
    - toc.follow
    - content.tabs.link
    - search.share
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotations  

markdown_extensions: 
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: ""
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: diagram
          class: diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_fenced_format {kwds: {mode: generic, tag: pre}}
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.blocks.admonition
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format {kwds: {mode: generic}}
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.caret
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.escapeall
  - pymdownx.details
  - pymdownx.progressbar
  - pymdownx.snippets
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - docs/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocs_pymdownx_material_extras